version: 2

updates:

- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily

# For dagger-compiler annotation processor.
- package-ecosystem: maven
  directory: "/advanced-achievements-plugin"
  schedule:
    interval: daily
