name: Push CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: adopt

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.1

    - name: Build project
      run: mvn -B package --file pom.xml

    - name: Validate formatting
      run: mvn validate formatter:validate

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2.3.0
      with:
        name: AdvancedAchievements Artifact
        path: advanced-achievements-plugin/target/*.jar
