name: Pull-Request CI

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - dev

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2.4.0

      - name: Setup JDK 17
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 17
          distribution: temurin

      - name: Cache local Maven repository
        uses: actions/cache@v2.1.7
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.4

      - name: Code Format
        run: mvn formatter:format

      - name: Build project
        run: mvn -B package --file pom.xml

      - name: Target Stage
        run: mkdir staging && cp advanced-achievements-plugin/target/*.jar staging

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: AdvancedAchievements Artifact
          path: staging
